### ISSUE TITLE
Get familiar with the tools

### ISSUE THREAD

**Issue by rw1nkler** [antmicro-labs/voice-assistant#13]
I have added links to useful resources to the project [Wiki](https://github.com/antmicro-labs/voice-assistant/wiki). Please, have a look at this.

**Comment by szymon-filipiak** [comment]
I think that everyone in the team now is building a solid understanding of the tools used in our project. Can you: @plonajakub @zawadzki-dawid @Marzecki @FilipKadziolka confirm that? When we will have comments from all colleagues, saying that they feel confident in this area, I would like to close this issue.

**Comment by zawadzki-dawid** [comment]
I confirm, issue can be closed.

**Comment by Marzecki** [comment]
I confirm too.

**Comment by plonajakub** [comment]
I feel the same @szymon-filipiak. We can close the issue.
