### ISSUE TITLE
Do we need to create board configuration with litex?

### ISSUE THREAD

**Issue by szymon-filipiak** [antmicro-labs/voice-assistant#15]
I have a question about creating a configuration for our board. 

**Do we need to do this?**

From what I've learned this step is required to be done once, and then binary can be uploaded onto multiple devices. Or is this a bad assumption?

I wonder **if You have any board configurations that we can use?**

My reason for asking that is setting up whole litex toolchain with Vivado is time-consuming, not only because of large files that must be downloaded but also someone must get familiar with the tools.
If You think that this step is important for us to learn, please let me know why, because I fear that I'm missing something. 
(Also, can we call for attention with @ Antmicro?) 

Summon Antmicro! :flight_arrival:

**Comment by kgugala** [comment]
you're right - you need to do it once. But this one time you have to do it. As we discussed in our meeting you don't have to start from LiteX and running everything in hardware. You should start with emulated system in Renode - this will significantly speed the development

**Comment by szymon-filipiak** [comment]
Ok, thanks!
