### ISSUE TITLE
LiteX Zephyr tutorial xc3sprog installation error

### ISSUE THREAD

**Issue by szymon-filipiak** [antmicro-labs/voice-assistant#16]
I think that I've found an error in the LiteX Zephyr tutorial on our wiki.

Installation of xc3sprog requires static library `libftdi` what is not said explicitly.

Another error is in the cmake command: 
`cmake ..` 
should be:
`cmake .`
or
`cd build
cmake ..`

Lastly link to the repository in the first point:
>    Download the xc3sprog program from this repository:

is malfunctioning.

**Comment by kgugala** [comment]
@szymon-filipiak can you update the wiki with your findings?

**Comment by szymon-filipiak** [comment]
@kgugala I wasn't sure if it is ok, because this wiki is linked to the video-processing project. I will do the update now, with your permission.

**Comment by kgugala** [comment]
if there is an obvious bug, feel free to fix it

**Comment by szymon-filipiak** [comment]
@kgugala It appears that I have no GitHub access to push to the origin of antmicro-labs/video-processing.wiki.git

**Comment by kgugala** [comment]
can you edit it in Github's editor?

**Comment by szymon-filipiak** [comment]
@kgugala The `Edit` button is not displayed to me so I suspect that I can't.

**Comment by kgugala** [comment]
I think we should reorganize Wikis, but for know @rw1nkler please update the wiki with the fixes described here

**Comment by szymon-filipiak** [comment]
Thanks for quick response and support @kgugala

**Comment by rw1nkler** [comment]
Sure, here you can also find ready working environment:
https://github.com/rw1nkler/litex-zephyr-build

It is tested on ubuntu 18.04

**Comment by rw1nkler** [comment]
I have fixed:
- [x]  link to antmicro repo
- [x] added proper prerequisites for xc3sprog on Debian
- [x] added missing `cd build` in xc3sprog installation section

@szymon-filipiak is that everything?

**Comment by szymon-filipiak** [comment]
@rw1nkler Yes, that's everything. Thank you!
