### ISSUE TITLE
TensorFlow fork as a submodule

### ISSUE THREAD

**Issue by plonajakub** [antmicro-labs/voice-assistant#17]
Is it possible to create a TensorFlow submodule in this repository similarly to [the demo](https://github.com/antmicro/litex-vexriscv-tensorflow-lite-demo) which in turn would be a fork of the newest version of the [main TensorFlow repository](https://github.com/tensorflow/tensorflow)?

**Comment by rw1nkler** [comment]
Probably you will need our fork of TensorFlow with the Zepyr port, but sure if it is more convenient, you can add it as a submodule.

**Comment by plonajakub** [comment]
I have been watching [Antmicro's fork](https://github.com/antmicro/tensorflow) for a while and it has been hard for me to go through the history of changes because of many available branches. It resulted in an idea to add things step by step to the clean version of the tensorflow repository to discover how things are made up. 

Today I discovered the [tf-demo-update branch](https://github.com/antmicro/tensorflow/tree/tf-demo-update) and things are much clearer. Am I correct that [comparing this branch to the tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/compare/master...antmicro:tf-demo-update) let me see all changes made to port TF Lite to Zephyr? If so, I do not now see any reason to fork the clean version of the tensorflow repo.

**Comment by kgugala** [comment]
I have forked both tensorflow and zephyr repositories to the antmicro-labs organization. Yous have write permissions there.

**Comment by kgugala** [comment]
> Today I discovered the [tf-demo-update branch](https://github.com/antmicro/tensorflow/tree/tf-demo-update) and things are much clearer. Am I correct that [comparing this branch to the tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/compare/master...antmicro:tf-demo-update) let me see all changes made to port TF Lite to Zephyr? If so, I do not now see any reason to fork the clean version of the tensorflow repo.

The easiest way to see the changes is to take a look at our pull request to main tensorflow repository https://github.com/tensorflow/tensorflow/pull/38111

**Comment by plonajakub** [comment]
> The easiest way to see the changes is to take a look at our pull request to main tensorflow repository tensorflow/tensorflow#38111

Thanks for the hint! Now I see everything I wanted to.

> I have forked both tensorflow and zephyr repositories to the antmicro-labs organization. Yous have write permissions there.

I really appreciate that the action was performed quickly. As I wrote, because the changes to the tensorflow/lite/micro are now clear there is no need to work on a clean version of TF repo. Anyway if you have nothing against we can manually push files from the mentioned pull request to https://github.com/antmicro-labs/tensorflow.

**Comment by kgugala** [comment]
> I really appreciate that the action was performed quickly. As I wrote, because the changes to the tensorflow/lite/micro are now clear there is no need to work on a clean version of TF repo. Anyway if you have nothing against we can manually push files from the mentioned pull request to https://github.com/antmicro-labs/tensorflow.

You should push the code to this fork and continue working in it (if you need to add anything to TF). You can crate a new branch and work there.

**Comment by plonajakub** [comment]
We will do as you said, thank you very much for your help.
