### ISSUE TITLE
Converting TF to TFLite

### ISSUE THREAD

**Issue by zawadzki-dawid** [antmicro-labs/voice-assistant#18]
I did a little research and found useful links that can help us in building well optimized TensorFlow Lite app.
- [**Converting TF to TFLite**](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/hello_world/create_sine_model.ipynb#scrollTo=i0FJe3Y-Gkac)
- [**TFLite converter**](https://www.tensorflow.org/lite/convert)
- [**Quantization**](https://www.tensorflow.org/lite/performance/post_training_quantization)

**Comment by plonajakub** [comment]
Hmm, maybe we should export such information to our wiki?

**Comment by szymon-filipiak** [comment]
Our wiki needs an update, but that is a different story.
