### ISSUE TITLE
The microphone driver

### ISSUE THREAD

**Issue by plonajakub** [antmicro-labs/voice-assistant#20]
We are close to hitting a milestone and having the micro_speech example running on Arty. Therefore I would like to ask if Antmicro will provide a driver for the microphone we were talking about at the first meeting. I am also sure that our team will have questions concerning the driver. Will some sort of documentation for the driver be available? If no, is it possible to organize a meeting to discuss our questions?

**Comment by kgugala** [comment]
We need to clean up it a little so it should be ready soon.
For now you can simulate the data input with some synthetic data. The microphone on the board will give you audio stream with the following parameters:

format: singed 24bit PCM, stereo, little endian
sample rate: 44100 Hz

**Comment by kgugala** [comment]
I have released the I2S IP core and Zephyr driver. The IP (with platfrom definition) is available here:
https://github.com/antmicro-labs/litex/tree/i2s_rx_stable

Zephyr driver and example application can be found in this repo https://github.com/antmicro-labs/zephyr/tree/i2s_rx_example

here https://github.com/antmicro-labs/zephyr/tree/i2s_rx_example/samples/drivers/i2s/litex is the example app with readme describing how the example can be run.

Please take a look on this and ping me when you have questions. We can schedule a telco and walk through the code

**Comment by plonajakub** [comment]
We will do as you said. I am sure that the meeting will be very helpful.

**Comment by szymon-filipiak** [comment]
I think we are ready for the telco. Can we schedule it for Friday at around 12 noon?

**Comment by rw1nkler** [comment]
Sure, @kgugala what do you think?

**Comment by kgugala** [comment]
sure, Friday 12 works for me

**Comment by rw1nkler** [comment]
Do you know how to use the driver? Have you run any program that uses it?

**Comment by szymon-filipiak** [comment]
Sorry for leaving this conversation in that state. We did found a way to use it and merged it into our app.
