### ISSUE TITLE
Debugging the application

### ISSUE THREAD

**Issue by szymon-filipiak** [antmicro-labs/voice-assistant#21]
We have created some custom code in TensorFlow in order to adapt micro_speech example, but for some reason, it's not running correctly. We have trouble seeing what really our software does when it's run in the simulation or on the board (we think that Zephyr is not booting successfully). 

Can we maybe schedule a call where you will share with us some tips and tricks for debugging? 

@kgugala @rw1nkler What do you think?

**Comment by rw1nkler** [comment]
Have you tried the GDB with Renode?
https://renode.readthedocs.io/en/latest/debugging/gdb.html

**Comment by zawadzki-dawid** [comment]
@rw1nkler I'm trying to debug our code but I don't feel comfortable to work with it, fixing bugs takes much time. Debugger don't seem to start at all and I think i did everything correctly but maybe I'm wrong. Our whole team would be glad to get quick intro to debugging in renode if it's possible.

**Comment by pgielda** [comment]
@zawadzki-dawid if you really discovered a bug in Renode (e.g. "Debugger don't seem to start at all") - please open an issue upstream in https://github.com/renode/renode with a proper bug report that actually contains info on how to reproduce the problem.

**Comment by zawadzki-dawid** [comment]
@pgielda I didn't mean that, I used not proper words to describe the problem, sorry about that. I did all the steps described in https://renode.readthedocs.io/en/latest/debugging/gdb.html and debugger is correctly reading symbols from our `zephyr.elf` and adding hooks works to but after executing `(litex-vexriscv) start` and `(gdb) continue` it don't seem to do something. I don't think that the tool has a bug, it's just a poor understanding of the tool.

**Comment by rw1nkler** [comment]
@zawadzki-dawid can you provide any guidance on how to reproduce your behaviour?
Maybe you could also attach binaries, even bitstream somewhere. 

Are you sure that you use proper gdb binary? We are using the `riscv` architecture whereas in the Renode tutorial you use the arm gdb (`arm-none-eabi-gdb`)

**Comment by rw1nkler** [comment]
Please, provide us also the source code of your applications! You can create the `examples` directory in the repository and put the code there. Maybe we are able to help you.

**Comment by zawadzki-dawid** [comment]
@rw1nkler i described our problem in more details in the [new issue](https://github.com/antmicro-labs/voice-assistant/issues/23).
