### ISSUE TITLE
Converting microphone input to data appropriate for TFLite

### ISSUE THREAD

**Issue by Marzecki** [antmicro-labs/voice-assistant#24]
We need to find a way to convert microphone input  to data that will be fed to the TFLite model. 
Conversion:
(singed 24bit PCM, stereo, little endian, 44100 Hz) => (signed 16bit PCM)

**Comment by kgugala** [comment]
converting `singed 24bit PCM -> signed 16bit PCM` is fairly easy - simply discard 8 least significant bits in each sample.

What about the rest of the parameters? Do they fit the model requirements?

**Comment by plonajakub** [comment]
I will check it and let you know.

**Comment by plonajakub** [comment]
I've done some research and here is what I've found:
- according to [audio recognition tutorial](https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md#custom-training-data) that was followed to create currently used NN model, the model was trained with **16-bit little-endian PCM-encoded** data from .wav files with **sample rate equal to 16kHz**
- moreover in [the paper](https://arxiv.org/pdf/1804.03209.pdf) describing the data, the full description can be found in the 6th section named _properties_; the data was encoded as 

> linear 16-bit single-channel PCM values, at a 16 kHz rate

so I conclude that the recordings were **mono** (and so should be our data).

**Comment by kgugala** [comment]
making mono, from stereo is also fairly easy - simply use mono microphone and discard single channel from recorded data (the ADC you have will always record stereo data, but if you use mono mic, both channels should be identical)

Changing sample rate will require adjusting the clocks we provide to the DAC

**Comment by szymon-filipiak** [comment]
Although the need for preprocessing has emerged I consider this task as done.
