### ISSUE TITLE
Use model's outputs

### ISSUE THREAD

**Issue by plonajakub** [antmicro-labs/voice-assistant#26]
We need to find a clever way to use the model's classification results to make our board being a device that could be classified as some sort of assistant. Feel free to list your ideas on this issue.

To start, I suggest creating some kind of menu that could be managed by voice commands. I going to implement this feature.

**Comment by plonajakub** [comment]
I've implemented a simple voice menu. You can see the code on [this](https://github.com/antmicro-labs/tensorflow/tree/assistant-services) branch. To use the menu extended model must be used with microphone input. If you have some ideas on how to make it shiny for the presentation let us know on this issue.

**Comment by kgugala** [comment]
This is a great news!! Good work!
Can we schedule a telco where you can present it?

**Comment by plonajakub** [comment]
Sure we can. The menu is rather simple and cannot be fully presented because the microphone handling code is still under development (as far as I know), but if you want to see the menu code I can present it. We can also have a small talk about possible peripherals usage; it is what the menu is lacking right now (except for LEDs).

 It seems that possible dates start from 27.05 in the afternoon. I will ask other members of our team when they are free to meet and post an exact possible meeting date below.

**Comment by plonajakub** [comment]
@kgugala, is it possible to meet on Wednesday 27.05 in between 12:30 - 15:00?

**Comment by kgugala** [comment]
Wednesday 14:00 fits me. I'll schedule the telco
