### ISSUE TITLE
Overlays and board config

### ISSUE THREAD

**Issue by szymon-filipiak** [antmicro-labs/voice-assistant#28]
I'm now trying to run our application and I'm getting confused with overlays. Do I need them? 

I have been provided with modified riscv32-litex-vexriscv.dtsi file and placed it inside my zephyr sources. Do I need to change values in overlay then? @kgugala or @rw1nkler

**Comment by kgugala** [comment]
If the dtsi contains all the configuration for your device you don't need the overlay

**Comment by szymon-filipiak** [comment]
Thanks! That's what I assumed.
