### ISSUE TITLE
Wierd tf behaviour. Probably out of memory on stack.

### ISSUE THREAD

**Issue by szymon-filipiak** [antmicro-labs/voice-assistant#29]
We are observing weird behaviour when we load a larger tf model.  We get false when matching the same values. If you have some time now we are working on it. If not, can you tell us how big can stack on our board be? Our model has approx 50kb @kgugala

**Comment by zawadzki-dawid** [comment]
We changed the model to the default one (yes, no) and we found out that voice recognition don't work. We tried to debug it but the problem seems to be outside of our purview. If you have time it would be great to schedule telco as soon as possible, even today, because we need to finish our project till friday.

**Comment by rw1nkler** [comment]
Yes, we can schedule the telco. @kgugala? The stack options can be found in the Zephyr Kernel Configuration (`General Kernel Options` submenu):

![Selection](https://user-images.githubusercontent.com/52699314/84874865-819e5e00-b085-11ea-8216-adf7dcc238ce.png)


The configuration can be changed using the `menuconfig` target:
https://docs.zephyrproject.org/latest/guides/kconfig/menuconfig.html#interactive-kconfig-interfaces

**Comment by kgugala** [comment]
I have a slot @2PM Is it OK for you to meet then?

**Comment by rw1nkler** [comment]
@szymon-filipiak @Marzecki @plonajakub  @zawadzki-dawid @FilipKadziolka

**Comment by szymon-filipiak** [comment]
Yes, let's schedule a meeting.

**Comment by szymon-filipiak** [comment]
We have detected a mismatch between the new model's training scripts tf version and tf version in our code. There is a fine probability that retraining the net will solve the problem. @zawadzki-dawid is doing it right now.
