### ISSUE TITLE
Flash example Zephyr binary to the Digilent board

### ISSUE THREAD

**Issue by plonajakub** [antmicro-labs/voice-assistant#3]
The project is meant to be run in the Zephyr OS in the LiteX/VexRiscv ecosystem on the Digilent Arty board. The board must be properly configured and the binary with Zephyr must be uploaded onto the board.

The goal is to flash the Arty board with example Zephyr binary and run it.

Responsible for this task is @szymon-filipiak.

References: [Wiki page](https://github.com/antmicro-labs/voice-assistant/wiki/LiteX---Zephyr-tutorial)

**Comment by szymon-filipiak** [comment]
I'm starting to work on this. Expect update in the evening.

**Comment by szymon-filipiak** [comment]
I've worked through the tutorial steps and read about the tools used there. I'm writing a document that will describe all of the tools in a more robust way than the tutorial on our wiki. I was doing all of this while downloading 18 Gb of Vivado files took place. I had plenty of time. :) 
As far as I understand the process of building configuration for our board should be done once, so don't worry. I will send you the binary if you want.

**Comment by szymon-filipiak** [comment]
I've worked through the process and successfully loaded hello world example onto the board! Later I will upload generated files that you can use to configure your boards.
