### ISSUE TITLE
Python Package for App

### ISSUE THREAD

**Issue by guillermocol** [antmicro-labs/voice-assistant#30]
Hi, 

I have started in the Python apps world recently and I have some questions that you may know the answer :)

I would like to know the best library or package to create the apk file. I saw that one popular is p4a and I have installed it; do you recommend any other way?

Also for the graphic interfaces for Python apps apart of kivi or tkinter or beware is there anything you may recommend that is better or works better with the app creation?

Thank you,

**Comment by szymon-filipiak** [comment]
Hi! Are you sure that you've posted your issue on the correct repo? 😃
