### ISSUE TITLE
Reinvite Filip Kądziołka

### ISSUE THREAD

**Issue by plonajakub** [antmicro-labs/voice-assistant#5]
We would be very gratefull for reinviting [Filip Kądziołka](https://github.com/FilipKadziolka) to our team. Unfortunetaly he lost his invitation and cannot join us. Thank you for help in advance.

**Comment by pgielda** [comment]
I did that. Please ping him to accept.

**Comment by plonajakub** [comment]
He has already accepted the invitation. Once more thanks for help and fast response!
